### ISSUE TITLE
Некорректно рассчитывается баланс при пополнении счета с итоговой суммой в рамках лимита

### ISSUE THREAD

**Issue by IgorChTest** [MarinaTret/javaqa-team-diplom-2#1]
## Описание

При пополнении счета итоговый баланс не рассчитывается как начальный баланс + сумма пополнения, а принимает значение суммы пополнения

## Локация дефекта

https://github.com/MarinaTret/javaqa-team-diplom-2/blob/72e6b49d432c79ed2a17404bced66dc6ec3ec6ab/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L73

## Шаги воспроизведения

1. Открыть [код программы](https://github.com/MarinaTret/javaqa-team-diplom-2/blob/saving/src/main/java/ru/netology/javaqadiplom/SavingAccount.java) в IDEA
2. Создать объект SavingAccount со значениями initialBalance = 2_000, minBalance = 1_000, maxBalance = 10_000, rate = 5
3. Добавить метод add с параметром amount = 3_000
4. Запустить тест

*Ожидаемый результат:* 5_000
*Фактический результат:* 3_000

## Тест
https://github.com/MarinaTret/javaqa-team-diplom-2/blob/72e6b49d432c79ed2a17404bced66dc6ec3ec6ab/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L9

## Скриншот
![error1](https://github.com/MarinaTret/javaqa-team-diplom-2/assets/151822183/aa6008dd-2fed-49c8-9b6e-dc2a3e7dcd29)

## Окружение
* **Операционная система:** Windows 11. Сборка 22631.2861
* **IDEA:** IntelliJ IDEA 2023.3.2 (Community Edition)
* **Java:** OpenJDK 11

**Comment by MarinaTret** [comment]
Исправлено, тест работает
