### ISSUE TITLE
Метод add в классе CreditAccount при пополнении баланса работает неверно

### ISSUE THREAD

**Issue by MarinaTret** [MarinaTret/javaqa-team-diplom-2#10]
**Описание**

Метод add в классе CreditAccount при пополнении баланса работает неверно

**Локация дефекта**

https://github.com/MarinaTret/javaqa-team-diplom-2/blob/df44a4ec161e2375b076ee29f1d28cd0f2d0e271/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L68

**Шаги воспроизведения**

1. Открыть СreditAccountTest в IDEA
2. Создать объект CreditAccount с параметрами (1_000, 5_000, 15) 
3. Добавить метод пополнения account.add(3_000)
4. Запустить тест

_Ожидаемый результат: 4_000_
_Фактический результат: 3_000_

**Тест**

https://github.com/MarinaTret/javaqa-team-diplom-2/blob/df44a4ec161e2375b076ee29f1d28cd0f2d0e271/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java#L76

**Скриншот**

![Снимок экрана 2024-02-16 100118](https://github.com/MarinaTret/javaqa-team-diplom-2/assets/151911577/48bdd68e-d72e-456f-b3f3-3088593f6536)

**Окружение**

- _Операционная система: Windows 11 Домашняя для одного языка. Версия 22H2. Сборка 22621.3007_
- _IDE: IntelliJ IDEA Community Edition 2023.3.2_
- _Java: OpenJDK 11._

**Comment by IgorChTest** [comment]
Исправлено, тест проходит
