### ISSUE TITLE
Неверный расчет процентов на отрицательный баланс счета CreditAccount при условии, что счёт не будет меняться год

### ISSUE THREAD

**Issue by MarinaTret** [MarinaTret/javaqa-team-diplom-2#3]
**Описание**

Неверно обрабатывается операция расчёта процентов на отрицательный баланс счёта на примере с положительным балансом

**Локация дефекта**

https://github.com/MarinaTret/javaqa-team-diplom-2/blob/14f385bc86e8e4ccdaefd28f65d9868c4feae0fe/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L86-L88

**Шаги воспроизведения**

1. Oткрыть СreditAccountTest в IDEA
2. Создать объект CreditAccount с параметрами (200, 5_000, 15)
3. Запустить тест

_Ожидаемый результат:_ расчет = 0
_Фактический результат:_ расчет = 30

 **Тест**

https://github.com/MarinaTret/javaqa-team-diplom-2/blob/df44a4ec161e2375b076ee29f1d28cd0f2d0e271/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java#L126

**Скриншот**

![Снимок экрана 2024-02-16 102122](https://github.com/MarinaTret/javaqa-team-diplom-2/assets/151911577/3c555b1e-69cd-4185-921c-ca8200eaf108)

**Окружение**
- _Операционная система: Windows 11 Домашняя для одного языка. Версия 22H2. Сборка 22621.3007_
- _IDE: IntelliJ IDEA Community Edition 2023.3.2_
- _Java: OpenJDK 11_

**Comment by IgorChTest** [comment]
Исправлено, тест проходит
