### ISSUE TITLE
Баланс уходит в минус при оплате суммы больше, чем сумма на счете.

### ISSUE THREAD

**Issue by IgorChTest** [MarinaTret/javaqa-team-diplom-2#4]
## Описание

При попытке оплаты суммы сверх имеющейся на счете баланс не может уходить в минус, поэтому итоговый баланс не должен измениться.

## Локация дефекта
https://github.com/MarinaTret/javaqa-team-diplom-2/blob/72e6b49d432c79ed2a17404bced66dc6ec3ec6ab/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L48-L49

## Шаги воспроизведения

1. Открыть [код программы](https://github.com/MarinaTret/javaqa-team-diplom-2/blob/saving/src/main/java/ru/netology/javaqadiplom/SavingAccount.java) в IDEA
2. Создать объект SavingAccount со значениями initialBalance = 2_000, minBalance = 1_000, maxBalance = 10_000, rate = 5
3. Добавить метод pay с параметром amount = 3_000
4. Запустить тест

*Ожидаемый результат:* 2_000
*Фактический результат:* -1_000

## Тест
https://github.com/MarinaTret/javaqa-team-diplom-2/blob/2693b10014ee14fc2072065a99617b36d75ab2e8/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L107

## Скриншот
![error3](https://github.com/MarinaTret/javaqa-team-diplom-2/assets/151822183/b16bfca4-f16d-46a3-b150-fc96a5b25721)

## Окружение
* **Операционная система:** Windows 11. Сборка 22631.2861
* **IDEA:** IntelliJ IDEA 2023.3.2 (Community Edition)
* **Java:** OpenJDK 11

**Comment by MarinaTret** [comment]
Исправлено, тест работает
