### ISSUE TITLE
Метод pay в классе CreditAccount при покупке на сумму больше, чем баланс карты + кредитный лимит, работает неверно

### ISSUE THREAD

**Issue by MarinaTret** [MarinaTret/javaqa-team-diplom-2#8]
**Описание**
При вызове метода оплата покупки на сумму больше, чем баланс + кредитный лимит, операция работает неверно

**Локация дефекта**

https://github.com/MarinaTret/javaqa-team-diplom-2/blob/14f385bc86e8e4ccdaefd28f65d9868c4feae0fe/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L42

**Шаги следования**

1. Открыть СreditAccountTest в IDEA
2. Создать объект CreditAccount с параметрами (2_000, 5_000, 15) и суммой покупки 8_000
3.  Запустить тест

Ожидаемый результат: покупку нельзя совершить, баланс карты 2_000
Фактический результат: -6_000

**Тест**

https://github.com/MarinaTret/javaqa-team-diplom-2/blob/df44a4ec161e2375b076ee29f1d28cd0f2d0e271/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java#L49

**Скриншот**

![Снимок экрана 2024-02-16 101007](https://github.com/MarinaTret/javaqa-team-diplom-2/assets/151911577/f857b18a-f964-472e-9cdd-90e49e6b268b)

**Окружение**

- Операционная система: Windows 11 Домашняя для одного языка. Версия 22H2. Сборка 22621.3007
- IDE: IntelliJ IDEA Community Edition 2023.3.2
- Java: OpenJDK 11

**Comment by IgorChTest** [comment]
Исправлено, тест проходит
