### ISSUE TITLE
Метод pay в классе CreditAccount при покупке в рамках баланса работает неверно

### ISSUE THREAD

**Issue by MarinaTret** [MarinaTret/javaqa-team-diplom-2#9]
**Описание**

Метод pay в классе CreditAccount при покупке в рамках баланса работает неверно

**Локация дефекта**

https://github.com/MarinaTret/javaqa-team-diplom-2/blob/df44a4ec161e2375b076ee29f1d28cd0f2d0e271/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L42

**Шаги воспроизведения**

1. Открыть СreditAccountTest в IDEA
2. Создать объект CreditAccount с параметрами (2_000, 5_000, 15) и суммой покупки 500
3. Запустить тест

_Ожидаемый результат:_ 1_500
_Фактический результат:_ -500

**Тест**

https://github.com/MarinaTret/javaqa-team-diplom-2/blob/df44a4ec161e2375b076ee29f1d28cd0f2d0e271/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java#L23

**Скриншот**

![Снимок экрана 2024-02-16 100555](https://github.com/MarinaTret/javaqa-team-diplom-2/assets/151911577/dbecb838-5313-4cf3-ba05-7de22093ecb7)

**Окружение**

- _Операционная система: Windows 11 Домашняя для одного языка. Версия 22H2. Сборка 22621.3007_
- _IDE: IntelliJ IDEA Community Edition 2023.3.2_
- _Java: OpenJDK 11_

**Comment by IgorChTest** [comment]
Исправлено, тест проходит
